version: "3.8"

volumes:
  db: {}

services:
  db:
    container_name: covid_postgres
    command: postgres -c listen_addresses='*'
    build: ./db/
    volumes:
      - db:/var/lib/postgresql
    environment:
     - POSTGRES_DB=covid
     - POSTGRES_USER=docker
     - POSTGRES_PASSWORD=docker
    ports:
      - "5433:5432"

  homework:
    build: ./homework/
    network_mode: host
    depends_on:
      - db
